environment:
    PYTHON_HOME: "C:\\Python37"

    CONAN_USERNAME: "qtproject"
    CONAN_UPLOAD: "https://api.bintray.com/conan/qtproject/conan"
    CONAN_ARCHS: "x86,x86_64"
    CONAN_UPLOAD_ONLY_WHEN_TAG: 1
    CONAN_VISUAL_RUNTIMES: "MD,MDd"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: "Release,Debug"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: "Release,Debug"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: "Release,Debug"
        - MINGW_CONFIGURATIONS: '7@x86@dwarf2@posix'
          CONAN_BUILD_TYPES: Release
        - MINGW_CONFIGURATIONS: '7@x86_64@seh@posix'
          CONAN_BUILD_TYPES: Release

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install -r conan_requirements.txt
  - conan user # It creates the conan data directory

build_script:
  - python build.py

